### PR TITLE
Switch to oauth2

### PR DESCRIPTION
**Pull request by beaufortfrancois**
In order for this patch to work, you'll have to create a project in the Google Developers Console, enable Google Drive API for this project, configure oauth and change TODO in `manifest.json`. See https://developer.chrome.com/apps/app_identity 

BUG=https://github.com/axenol/drive-quick-search/issues/15

### CODE REVIEW

**Comment by axenol** [comment]
I changed the TODO but now it's not working for me. What's happening is when I load the extension it redirects me to Chrome sign-in page (chrome://chrome-signin/?source=5), when I am already signed in.

**Comment by axenol** [comment]
Tried with a new client ID with no luck.

**Comment by beaufortfrancois** [comment]
Can you add me to Google Console Project (beaufortfrancois@gmail.com) so that I can see if auth and api are well configured?
Moreover, what is your extension ID?

**Comment by axenol** [comment]
I just did. 
ID: ddebdlfmldojeofgkeocjdkloocegmae

**Comment by beaufortfrancois** [comment]
Thanks!
Did you change 'TODO.apps.googleusercontent.com' to '608686014163-6o9nqk0bs8oaaf7qo52ng36aioggb3q4.apps.googleusercontent.com' in your new manifest?

**Comment by axenol** [comment]
Yes I did.

**Comment by beaufortfrancois** [comment]
Just to be sure, when you mean _you're already signed in_, does that mean you have a Chrome Profile linked to a Google Account (with your bookmarks synced for instance)?
https://support.google.com/chrome/answer/185277?hl=en

**Comment by axenol** [comment]
Yes, I have a Google linked to Chrome. Did you try running the extension
yourself? Does that work for you?

**Comment by beaufortfrancois** [comment]
It does. That's why I'm surprised ;)
Let me think again...

**Comment by axenol** [comment]
I tried it on a Linux machine let me try with my Windows Chrome too.

**Comment by beaufortfrancois** [comment]
Can you try https://chrome.google.com/webstore/detail/joeillepcbfmppkkjbldfgoofkfkbkij which is simply your extension with my custom manifest "client_id"?
I also invited you to my Google Console Project so that you see what might be different.
It works well on my Chromebook as far as I can tell.

**Comment by axenol** [comment]
Oddly enough, it works :) It's exaclty like yours except I also added a public "Key for browser applications" for old OAuth. And the old one still doesn't work.

**Comment by axenol** [comment]
Maybe it's time to report a Chrome bug :)

**Comment by beaufortfrancois** [comment]
Can you try with a brand new Google developer project and see if that
changes anything?

**Comment by axenol** [comment]
Tried. Didn't work. Looks like a problem with my account or browser. I will try with Chromium now.

**Comment by axenol** [comment]
So it works now but I have no idea why. Here's what I did to fix it.
Installed Chromium. It was already signed in to my account. Tried the extension on Chromium with the new client ID, it didn't work. Signed out of Chrome Sync on Chromium and tried again. The Chrome sign-in page appeared again when I loaded the extension, entered my password and it worked. Oddly enough now it works in my Chrome too, both with the new and old client ID.

Must be some weird bug, I have no idea what's going on.

**Comment by axenol** [comment]
Ok, figured it out. Turns out the problem was the extension ID I entered in Google Console didn't match the local extension ID. I was using the Web Store ID(ddebdlfmldojeofgkeocjdkloocegmae) but I needed to use the one generated locally. Turns out "Copy key to your manifest" part  in https://developer.chrome.com/apps/app_identity was important :). Now I fixed everything and committed the changes.

**Comment by beaufortfrancois** [comment]
Awesome! Glad we've figured it out eventually ;)

**Pull request merged**
